name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.rst'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.rst'
  workflow_dispatch:

jobs:
  codestyle:
    name: Check code style issues
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install Ruff
      run: python -m pip install ruff

    - name: Test with Ruff
      run: ruff check .

    - name: Lint with Ruff
      run: ruff format --check .