name: Build and Release

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag for the build'
        required: true
        default: 'v1.3.7.0' # Hard-Coded First Release

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.13, 3.7]
        include:
          - python-version: 3.13
            target: "hPyT-Preview-${{ github.event.inputs.release_tag || github.event.release.tag_name }}"
          - python-version: 3.7
            target: "hPyT-Preview-win7-${{ github.event.inputs.release_tag || github.event.release.tag_name }}"

    steps:
      - name: Checkout a specific release
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.release_tag || github.event.release.tag_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install UPX using Chocolatey
        run: |
          choco install upx -y
          echo "UPX_DIR=C:\Program Files\upx" >> $env:GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyinstaller_versionfile
          pip install -r requirements.txt

      - name: Generate version file
        run: python version.py ${{ github.event.inputs.release_tag || github.event.release.tag_name }}

      - name: Build executable
        run: |
          pyinstaller --noconfirm --onefile --windowed `
            --icon="app-assets/icon.ico" `
            --name="${{ matrix.target }}" `
            --clean `
            --upx-dir="$env:UPX_DIR" `
            --version-file="versionfile.txt" `
            --add-data="app-assets;app-assets" `
            --exclude-module="numpy" `
            --exclude-module="cv2" `
            --hidden-import="customtkinter" `
            main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-win64
          path: dist/${{ matrix.target }}.exe

      - name: Upload to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/${{ matrix.target }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}